# yaml 配置
version: "3.7"
services:
  mysql:latest:
    image: "mysql:9.1.0"
    ports:
      - "3037:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "123"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis:
    image: "redis:7.4.1"
    ports:
      - "6379:6379"
  bluebell_app:
    build: .
    command: sh -c "./wait-for.sh mysql:latest:3307 redis:6379 -- ./bluebell_app ./conf/config.yaml"
    depends_on:
      - mysql:latest
      - redis
    ports:
      - "8888:8084"